from __future__ import annotations

from .models import (
    AlertDefinition,
    AlertScope,
    AlertSeverity,
    AssetDefinition,
    BackgroundDefinition,
    BackendDefinition,
    BackendType,
    CanBusDefinition,
    CanMessageDefinition,
    CanMode,
    CanSignalDecodeDefinition,
    DashboardProject,
    Endianness,
    FallbackMode,
    HardwareRuleDefinition,
    LatchBehavior,
    LayoutAnchor,
    NumericRange,
    PageDefinition,
    PageType,
    PeripheralDefinition,
    PeripheralType,
    ProfileDefinition,
    ProjectMetadata,
    Resolution,
    SignalDataType,
    SignalDefinition,
    SignalFallbackPolicy,
    SignalFormatting,
    SignalFreshnessPolicy,
    SignalMapping,
    ThemeDefinition,
    ThemeTokenSet,
    WidgetBinding,
    WidgetDataBehavior,
    WidgetDataStateBehavior,
    WidgetDefinition,
    WidgetLayout,
)


def create_example_project() -> DashboardProject:
    return DashboardProject(
        metadata=ProjectMetadata(
            id="demo-motorsport-platform",
            name="Demo Motorsport Dashboard Platform",
            version="0.1.0",
            schema_version="1.0.0",
            description="Example project definition covering sim and FSAE use cases.",
            author="OpenAI Codex",
            created_at_iso="2026-03-18T00:00:00Z",
            updated_at_iso="2026-03-18T00:00:00Z",
        ),
        assets=[
            AssetDefinition(
                id="bg-gt3",
                type="image",
                path="assets/sample-backgrounds/gt3.png",
                description="Placeholder GT3 background",
            )
        ],
        signals=[
            SignalDefinition(
                id="vehicle.engine.rpm",
                display_name="RPM",
                category="engine",
                data_type=SignalDataType.INTEGER,
                units="rpm",
                expected_range=NumericRange(min=0, max=12000),
                formatting=SignalFormatting(decimals=0, unit_display="hidden"),
                freshness=SignalFreshnessPolicy(stale_after_ms=200, missing_after_ms=1000),
                fallback=SignalFallbackPolicy(mode=FallbackMode.FREEZE_LAST),
                tags=["sim", "vehicle", "powertrain"],
            ),
            SignalDefinition(
                id="vehicle.transmission.gear",
                display_name="Gear",
                category="drivetrain",
                data_type=SignalDataType.STRING,
                freshness=SignalFreshnessPolicy(stale_after_ms=200, missing_after_ms=1000),
                fallback=SignalFallbackPolicy(mode=FallbackMode.DEFAULT_VALUE, default_value="-"),
            ),
            SignalDefinition(
                id="vehicle.speed",
                display_name="Speed",
                category="vehicle",
                data_type=SignalDataType.NUMBER,
                units="kmh",
                expected_range=NumericRange(min=0, max=400),
                formatting=SignalFormatting(decimals=0, unit_display="suffix"),
                freshness=SignalFreshnessPolicy(stale_after_ms=250, missing_after_ms=1200),
                fallback=SignalFallbackPolicy(mode=FallbackMode.FREEZE_LAST),
            ),
            SignalDefinition(
                id="vehicle.battery.voltage",
                display_name="Battery Voltage",
                category="electrical",
                data_type=SignalDataType.NUMBER,
                units="V",
                expected_range=NumericRange(min=0, max=800),
                formatting=SignalFormatting(decimals=1, unit_display="suffix"),
                freshness=SignalFreshnessPolicy(stale_after_ms=500, missing_after_ms=2000),
                fallback=SignalFallbackPolicy(mode=FallbackMode.DEFAULT_VALUE, default_value=None),
            ),
            SignalDefinition(
                id="system.can.bus0.health",
                display_name="CAN Bus Health",
                category="system",
                data_type=SignalDataType.ENUM,
                enum_map={"ok": "OK", "degraded": "Degraded", "timeout": "Timeout", "down": "Down"},
                freshness=SignalFreshnessPolicy(stale_after_ms=1000, missing_after_ms=3000),
                fallback=SignalFallbackPolicy(mode=FallbackMode.DEFAULT_VALUE, default_value="down"),
            ),
        ],
        backends=[
            BackendDefinition(
                id="sim-hub",
                type=BackendType.IRACING_HUB,
                name="Windows Simulator Hub",
                config={"protocol": "websocket", "url": "ws://telemetry-hub.local:8765"},
            ),
            BackendDefinition(
                id="vehicle-can",
                type=BackendType.CAN,
                name="Primary Vehicle CAN",
                config={"bus_id": "can0"},
            ),
            BackendDefinition(
                id="preview-mock",
                type=BackendType.MOCK,
                name="Preview Mock Backend",
                config={"scenario": "gt3-demo"},
            ),
        ],
        can_buses=[
            CanBusDefinition(id="can0", interface_name="can0", bitrate=500000, mode=CanMode.CLASSIC, health_timeout_ms=1000)
        ],
        can_messages=[
            CanMessageDefinition(
                id="msg-bms-status",
                bus_id="can0",
                arbitration_id="0x301",
                name="BMS Status",
                expected_period_ms=100,
                timeout_ms=300,
            )
        ],
        can_signals=[
            CanSignalDecodeDefinition(
                id="can-bms-pack-voltage",
                message_id="msg-bms-status",
                name="Pack Voltage",
                start_bit=0,
                bit_length=16,
                endianness=Endianness.LITTLE,
                signed=False,
                scale=0.1,
                units="V",
                expected_range=NumericRange(min=0, max=800),
            )
        ],
        mappings=[
            SignalMapping(
                id="map-rpm-iracing",
                signal_id="vehicle.engine.rpm",
                backend_id="sim-hub",
                source_type="backend-field",
                source_ref="iracing.engine.rpm",
            ),
            SignalMapping(
                id="map-gear-iracing",
                signal_id="vehicle.transmission.gear",
                backend_id="sim-hub",
                source_type="backend-field",
                source_ref="iracing.car.gear",
            ),
            SignalMapping(
                id="map-speed-iracing",
                signal_id="vehicle.speed",
                backend_id="sim-hub",
                source_type="backend-field",
                source_ref="iracing.vehicle.speedKmh",
            ),
            SignalMapping(
                id="map-pack-voltage-can",
                signal_id="vehicle.battery.voltage",
                backend_id="vehicle-can",
                source_type="can-decode",
                source_ref="can-bms-pack-voltage",
            ),
            SignalMapping(
                id="map-can-health-derived",
                signal_id="system.can.bus0.health",
                backend_id="vehicle-can",
                source_type="formula",
                source_ref="'timeout' if signal('vehicle.battery.voltage') is None else 'ok'",
            ),
        ],
        themes=[
            ThemeDefinition(
                id="theme-gt3-dark",
                name="GT3 Dark",
                tokens=ThemeTokenSet(
                    colors={
                        "color.background": "#05070A",
                        "color.panel": "#11161C",
                        "color.text.primary": "#F7FAFC",
                        "color.text.secondary": "#A5B3C2",
                        "color.status.warning": "#F2C94C",
                        "color.status.critical": "#EB5757",
                        "color.rpm.shift": "#FF8A00",
                        "color.rpm.limiter": "#FF3B30",
                    },
                    fonts={"font.numeric.primary": "Orbitron", "font.label": "Inter"},
                    radii={"sm": 4, "md": 8, "lg": 14},
                    borders={"thin": 1, "thick": 2},
                ),
            )
        ],
        widgets=[
            WidgetDefinition(
                id="widget-gear",
                type="gear-display",
                name="Gear",
                layout=WidgetLayout(x=286, y=80, width=180, height=180, anchor=LayoutAnchor.TOP_LEFT, z_index=20),
                bindings=[WidgetBinding(key="gear", signal_id="vehicle.transmission.gear")],
                props={"align": "center"},
                style_overrides={"font_size": 120},
            ),
            WidgetDefinition(
                id="widget-speed",
                type="numeric-readout",
                name="Speed",
                layout=WidgetLayout(x=520, y=96, width=180, height=100, anchor=LayoutAnchor.TOP_LEFT, z_index=20),
                bindings=[WidgetBinding(key="value", signal_id="vehicle.speed")],
                props={"label": "SPEED"},
            ),
            WidgetDefinition(
                id="widget-rpm",
                type="rpm-bar",
                name="RPM Bar",
                layout=WidgetLayout(x=40, y=24, width=720, height=40, anchor=LayoutAnchor.TOP_LEFT, z_index=30),
                bindings=[WidgetBinding(key="rpm", signal_id="vehicle.engine.rpm")],
                props={"max_rpm": 10000, "shift_rpm": 9000, "limiter_rpm": 9800},
            ),
            WidgetDefinition(
                id="widget-batt-voltage",
                type="numeric-readout",
                name="Pack Voltage",
                layout=WidgetLayout(x=40, y=360, width=180, height=60, anchor=LayoutAnchor.TOP_LEFT, z_index=20),
                bindings=[WidgetBinding(key="value", signal_id="vehicle.battery.voltage")],
                props={"label": "PACK V"},
                data_behavior=WidgetDataBehavior(
                    on_missing=WidgetDataStateBehavior.PLACEHOLDER,
                    on_stale=WidgetDataStateBehavior.GRAY_OUT,
                    placeholder_text="---",
                ),
            ),
        ],
        pages=[
            PageDefinition(
                id="page-main-gt3",
                name="Main GT3 Page",
                reference_resolution=Resolution(width=800, height=480),
                type=PageType.DASHBOARD,
                background=BackgroundDefinition(color="#05070A", image_asset_id="bg-gt3"),
                theme_override_id="theme-gt3-dark",
                widget_ids=["widget-rpm", "widget-gear", "widget-speed", "widget-batt-voltage"],
            )
        ],
        alerts=[
            AlertDefinition(
                id="alert-can-timeout",
                name="CAN Timeout",
                severity=AlertSeverity.CRITICAL,
                priority=100,
                scope=AlertScope.GLOBAL,
                condition="signal('system.can.bus0.health') == 'timeout'",
                latch_behavior=LatchBehavior.LATCHED_UNTIL_ACK,
                acknowledgment_required=True,
                activation_delay_ms=100,
                clear_delay_ms=250,
                output_targets=["output.warning_led_main"],
            ),
            AlertDefinition(
                id="alert-low-battery",
                name="Low Battery Voltage",
                severity=AlertSeverity.WARNING,
                priority=75,
                scope=AlertScope.PROFILE,
                condition="signal('vehicle.battery.voltage') != None and signal('vehicle.battery.voltage') < 300",
            ),
        ],
        peripherals=[
            PeripheralDefinition(
                id="peripheral-shiftbar",
                type=PeripheralType.SHIFT_LED_BAR,
                name="Primary Shift Bar",
                config={"channel_count": 15, "transport": "serial", "port": "/dev/ttyUSB0"},
            ),
            PeripheralDefinition(
                id="peripheral-warning-led",
                type=PeripheralType.INDICATOR_LIGHT,
                name="Warning LED",
                config={"gpio_pin": 18, "active_high": True},
            ),
        ],
        hardware_rules=[
            HardwareRuleDefinition(
                id="rule-shiftbar-rpm",
                peripheral_id="peripheral-shiftbar",
                logical_output_id="output.shift_bar_primary",
                trigger="signal('vehicle.engine.rpm')",
                action={"mode": "rpm-progress", "start_rpm": 6000, "shift_rpm": 9000, "limiter_rpm": 9800},
            ),
            HardwareRuleDefinition(
                id="rule-warning-led-critical-alert",
                peripheral_id="peripheral-warning-led",
                logical_output_id="output.warning_led_main",
                trigger="has_active_alert_severity('critical')",
                action={"mode": "flash", "hz": 4, "color": "red"},
            ),
        ],
        profiles=[
            ProfileDefinition(
                id="profile-gt3",
                name="GT3 Sim",
                backend_ids=["sim-hub", "preview-mock"],
                mapping_ids=["map-rpm-iracing", "map-gear-iracing", "map-speed-iracing"],
                page_ids=["page-main-gt3"],
                default_page_id="page-main-gt3",
                theme_id="theme-gt3-dark",
                peripheral_ids=["peripheral-shiftbar"],
                hardware_rule_ids=["rule-shiftbar-rpm"],
                tags=["sim", "gt3"],
            ),
            ProfileDefinition(
                id="profile-fsae",
                name="FSAE Vehicle",
                backend_ids=["vehicle-can"],
                mapping_ids=["map-pack-voltage-can", "map-can-health-derived"],
                page_ids=["page-main-gt3"],
                default_page_id="page-main-gt3",
                theme_id="theme-gt3-dark",
                alert_ids=["alert-can-timeout", "alert-low-battery"],
                peripheral_ids=["peripheral-warning-led"],
                hardware_rule_ids=["rule-warning-led-critical-alert"],
                tags=["vehicle", "fsae", "can"],
            ),
        ],
    )


EXAMPLE_PROJECT = create_example_project()
